class DynamoDBDoctorException(Exception):
    ...

class ModelCreationException(DynamoDBDoctorException):
    ...

class MissingAttributeException(DynamoDBDoctorException):
    ...

class DeserializationException(DynamoDBDoctorException):
    ...